//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_tbl()
        {
            this.Information_tbl = new HashSet<Information_tbl>();
            this.Order_tbl = new HashSet<Order_tbl>();
        }
    
        public int Cust_Id { get; set; }
        public int Manager_Id { get; set; }
        public string Cust_name { get; set; }
        public string Cust_phone { get; set; }
        public string Cust_phone2 { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int House_num { get; set; }
        public int Apartment_num { get; set; }
        public int Floor { get; set; }
        public string Lat { get; set; }
        public string Lan { get; set; }
    
        public virtual Manager_tbl Manager_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Information_tbl> Information_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_tbl> Order_tbl { get; set; }
    }
}
