//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Super_FastEntities : DbContext
    {
        public Super_FastEntities()
            : base("name=Super_FastEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_tbl> Customer_tbl { get; set; }
        public virtual DbSet<Information_tbl> Information_tbl { get; set; }
        public virtual DbSet<Manager_tbl> Manager_tbl { get; set; }
        public virtual DbSet<Messengers_tbl> Messengers_tbl { get; set; }
        public virtual DbSet<Order_tbl> Order_tbl { get; set; }
    }
}
