//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_tbl
    {
        public int Order_Id { get; set; }
        public int Manager_Id { get; set; }
        public int Cust_Id { get; set; }
        public int Amount_packages { get; set; }
        public Nullable<int> Messenger_Id { get; set; }
    
        public virtual Customer_tbl Customer_tbl { get; set; }
        public virtual Manager_tbl Manager_tbl { get; set; }
        public virtual Messengers_tbl Messengers_tbl { get; set; }
    }
}
